name: My Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-cmjr897qd2ns73bkupo0
          api-key: rnd_g3IusvxDeKaqbvxxMXBYAG2CJtxc
          wait-for-success: true